contributors:
  data entry:
    dum:
      - Elisabeth de Bruijn
      - Cecile Vermaas
      - Mike Kestemont
      - Remco Sleiderink
    gmh:
      - Mike Kestemont
    non:
      - Katarzyna Kapitan
    default:
      - Jean-Baptiste Camps
  encoding:
    metadata:
      - Kelly Christensen
    text:
      - Théo Moins
file paths:
  heurist database: heurist.db
  graph database: kuzu_db
  output directory: texts
  text TEI model: tei_base_text.xml
